version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_report
      POSTGRES_USER: report
      POSTGRES_PASSWORD: report
    ports:
      - "55489:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/test_report
      DB_USERNAME: report
      DB_PASSWORD: report
      COLUMN_CONFIG_PATH: classpath:config/column-config.json
      PORT: 18080
    depends_on:
      - db
    ports:
      - "18080:18080"

volumes:
  db-data:
